name: macOS 13
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate formulas
        run: |
          status=0
          for f in Formula/**/*.rb; do
            ruby -c "$f" || status=1
          done
          exit $status
