name: brew test-bot
on:
  push:
    branches: master
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: test
        run: echo testcx
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

